# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# https://starship.rs/config/#character
[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red) '

# https://starship.rs/config/#cmd_duration
[cmd_duration]
min_time = 5000
format = 'underwent [$duration](bold yellow)'

# https://starship.rs/config/#git_branch
[git_branch]
disabled = false
# ignore_branches = ['master', 'main']

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# https://starship.rs/config/#aws
[aws]
disabled = false
style = "yellow"
symbol = ''
format = '\[AWS\] [$symbol($profile )(\($region\) )(\[$duration\] )]($style)'

# https://starship.rs/config/#terraform
[terraform]
disabled = false
symbol = ''
format = '\[TF\] [$symbol$workspace]($style) '

# https://starship.rs/config/#kubernetes
[kubernetes]
disabled = false
contexts = [
  # https://starship.rs/advanced-config/#style-strings
  # DEV/TEST clusters
  { context_pattern = ".+@k8s-integration-dev.+", context_alias = "k8s-int-dev", style = "bold #808080" },
  { context_pattern = ".+@apigw-integration-DEV.+", context_alias = "apigw-int-dev", style = "underline bold #808080" },
  { context_pattern = ".+@k8s-integration-test.+", context_alias = "k8s-int-test", style = "bold #808080" },
  { context_pattern = ".+@apigw-integration-TEST.+", context_alias = "apigw-int-test", style = "underline bold #808080" },
  { context_pattern = ".+@k8s-validation-dev.+", context_alias = "k8s-val-dev", style = "bold #808080" },
  { context_pattern = ".+@apigw-validation-DEV.+", context_alias = "apigw-val-dev", style = "underline bold #808080" },
  { context_pattern = ".+@k8s-validation-test.+", context_alias = "k8s-val-test", style = "bold #808080" },
  { context_pattern = ".+@apigw-validation-TEST.+", context_alias = "apigw-val-test", style = "underline bold #808080" },
  { context_pattern = ".+@k8s-production-dev.+-central-1", context_alias = "k8s-prod-EU-dev", style = "bold #808080" },
  { context_pattern = ".+@k8s-production-test.+-central-1", context_alias = "k8s-prod-EU-test", style = "bold #808080" },
  { context_pattern = ".+-dev-.+", style = "bold #808080" },
  { context_pattern = ".+-test-.+", style = "bold #808080" },
  # PROD clusters
  { context_pattern = ".+@k8s-integration.+", context_alias = "k8s-int", style = "bold green" },
  { context_pattern = ".+@apigw-integration.+", context_alias = "apigw-int", style = "underline bold green" },
  { context_pattern = ".+@k8s-validation.+", context_alias = "k8s-val", style = "bold #FFA500" },
  { context_pattern = ".+@apigw-validation.+", context_alias = "apigw-val", style = "underline bold #FFA500" },
  { context_pattern = ".+@k8s-production-eu-central-1", context_alias = "k8s-prod-EU", style = "bold red" },
  { context_pattern = ".+@k8s-production-eu-west-1", context_alias = "k8s-prod-EUW", style = "bold red" },
  { context_pattern = ".+@k8s-production-us-east-1", context_alias = "k8s-prod-US", style = "bold red" },
  { context_pattern = ".+@k8s-production-cn-north-1", context_alias = "k8s-prod-CHINA", style = "bold red" },
  { context_pattern = ".+@apigw-production-eu-central-1", context_alias = "apigw-prod-EU", style = "underline bold red" },
  { context_pattern = ".+@apigw-production-eu-west-1", context_alias = "apigw-prod-EUW", style = "underline bold red" },
  { context_pattern = ".+@apigw-production-us-east-1", context_alias = "apigw-prod-US", style = "underline bold red" },
  { context_pattern = ".+@apigw-production-cn-north-1", context_alias = "apigw-prod-CHINA", style = "underline bold red" },
]

# https://starship.rs/config/#nix_shell
[nix_shell]
disabled = true
impure_msg = 'devbox'
format = 'via [$symbol$state](bold blue) '
